#!/bin/sh
# Copyright 2022 Simon McVittie
# SPDX-License-Identifier: GPL-2.0-or-later

set -eu

vendor=debian
suite=testing

if [ -z "${AUTOPKGTEST_TEST_UNINSTALLED-}" ]; then
    export AUTOPKGTEST_TEST_INSTALLED=yes
    build_docker=autopkgtest-build-docker
else
    build_docker=tools/autopkgtest-build-docker
fi

if ! "$build_docker" --vendor="$vendor" --release="$suite"; then
    echo "SKIP: Unable to build autopkgtest/$vendor:$suite container"
    exit 77
fi

export AUTOPKGTEST_TEST_DOCKER="autopkgtest/$vendor:$suite"
export PYTHONUNBUFFERED=1
# Wrapping the test in annotate-output helps to distinguish the output of
# the autopkgtest that is running these tests from the output of the
# autopkgtest that is under test.
exec annotate-output ./tests/autopkgtest DockerRunner
